#!/bin/bash
lein update-in :dependencies conj "[org.clojure/tools.nrepl \"0.2.12\"]" -- update-in :plugins conj "[refactor-nrepl \"2.3.0-SNAPSHOT\"]" -- update-in :plugins conj "[cider/cider-nrepl \"0.15.0-SNAPSHOT\"]" -- repl :headless :port 7000
