{:identity nil,
 :ssl-client-cert nil,
 :cookies {"ring-session"
           {:value "8ca85b37-9dea-40e0-9a20-fa4ba18b5d02"}},
 :remote-addr "10.0.2.2",
 :params {},
 :flash nil,
 :handler-type :undertow,
 :route-handler #function[compojure.core/make-route/fn--27037],
 :route-params {},
 :headers {"host" "localhost:3000", "user-agent" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36", "cookie" "ring-session=8ca85b37-9dea-40e0-9a20-fa4ba18b5d02", "referer" "http://localhost:3000/login", "connection" "keep-alive", "upgrade-insecure-requests" "1", "accept" "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8", "accept-language" "en-US,en;q=0.8", "accept-encoding" "gzip, deflate, sdch", "cache-control" "max-age=0"},
 :server-port 3000,
 :content-length -1,
 :form-params {},
 :compojure/route [:get "/"],
 :session/key "8ca85b37-9dea-40e0-9a20-fa4ba18b5d02",
 :server-exchange #object[io.undertow.server.HttpServerExchange 0x789bbd9a "HttpServerExchange{ GET / request {Accept=[text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8], Accept-Language=[en-US,en;q=0.8], Cache-Control=[max-age=0], Accept-Encoding=[gzip, deflate, sdch], User-Agent=[Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36], Connection=[keep-alive], Cookie=[ring-session=8ca85b37-9dea-40e0-9a20-fa4ba18b5d02], Referer=[http://localhost:3000/login], Upgrade-Insecure-Requests=[1], Host=[localhost:3000]} response {Server=[undertow]}}"],
 :query-params {},
 :content-type nil,
 :path-info "/",
 :character-encoding nil,
 :context "",
 :uri "/",
 :server-name "localhost",
 :query-string nil,
 :body #object[io.undertow.io.UndertowInputStream 0x7d62d89f "io.undertow.io.UndertowInputStream@7d62d89f"],
 :multipart-params {},
 :scheme :http,
 :request-method :get,
 :route-middleware #function[clojure.core/comp/fn--4727],
 :session {:ring.middleware.anti-forgery/anti-forgery-token "Ga1uSN/hjGu3Ue8prwo2EcZdhUC0KsBlyo2jaOMs1NV6cEqMj1Zu/uFQJ7+5+pykEi+SkgCtELE/J9cc", :identity "test"}}
